language: node_js

matrix:
  include:
    - os: linux
      node_js: 6
      env: CC=clang CXX=clang++ npm_config_clang=1
    - os: osx
      node_js: 6

addons:
  apt:
    packages:
      - clang-3.3
      - libx11-dev
      - libxkbfile-dev

notifications:
  email:
    on_success: never
    on_failure: change

script: 'npm test'

git:
  depth: 1
