language: node_js

node_js: 6

os:
  - linux
  - osx

addons:
  apt:
    packages:
      - libx11-dev
      - libxkbfile-dev

notifications:
  email:
    on_success: never
    on_failure: change

script: 'npm test'

git:
  depth: 1
